<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Objectives" data-toc-modified-id="Objectives-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Objectives</a></span></li><li><span><a href="#What-&amp;-Why-of-Linear-Algebra" data-toc-modified-id="What-&amp;-Why-of-Linear-Algebra-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>What &amp; Why of Linear Algebra</a></span></li><li><span><a href="#Scalars,-Vectors,-and-Tensors!-Oh-My!" data-toc-modified-id="Scalars,-Vectors,-and-Tensors!-Oh-My!-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Scalars, Vectors, and Tensors! Oh My!</a></span><ul class="toc-item"><li><span><a href="#Scalars" data-toc-modified-id="Scalars-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Scalars</a></span></li><li><span><a href="#Vectors" data-toc-modified-id="Vectors-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Vectors</a></span><ul class="toc-item"><li><span><a href="#Code-for-Vectors" data-toc-modified-id="Code-for-Vectors-3.2.1"><span class="toc-item-num">3.2.1&nbsp;&nbsp;</span>Code for Vectors</a></span></li><li><span><a href="#Math-with-Vectors" data-toc-modified-id="Math-with-Vectors-3.2.2"><span class="toc-item-num">3.2.2&nbsp;&nbsp;</span>Math with Vectors</a></span><ul class="toc-item"><li><span><a href="#Vector-Addition" data-toc-modified-id="Vector-Addition-3.2.2.1"><span class="toc-item-num">3.2.2.1&nbsp;&nbsp;</span>Vector Addition</a></span></li><li><span><a href="#Vector-Multiplication" data-toc-modified-id="Vector-Multiplication-3.2.2.2"><span class="toc-item-num">3.2.2.2&nbsp;&nbsp;</span>Vector Multiplication</a></span></li></ul></li></ul></li><li><span><a href="#Matrices-and-Tensors" data-toc-modified-id="Matrices-and-Tensors-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>Matrices and Tensors</a></span><ul class="toc-item"><li><span><a href="#Code-for-Matrices-and-Tensors" data-toc-modified-id="Code-for-Matrices-and-Tensors-3.3.1"><span class="toc-item-num">3.3.1&nbsp;&nbsp;</span>Code for Matrices and Tensors</a></span></li><li><span><a href="#Math-with-Tensors" data-toc-modified-id="Math-with-Tensors-3.3.2"><span class="toc-item-num">3.3.2&nbsp;&nbsp;</span>Math with Tensors</a></span><ul class="toc-item"><li><span><a href="#Addition" data-toc-modified-id="Addition-3.3.2.1"><span class="toc-item-num">3.3.2.1&nbsp;&nbsp;</span>Addition</a></span></li><li><span><a href="#Dot-Product" data-toc-modified-id="Dot-Product-3.3.2.2"><span class="toc-item-num">3.3.2.2&nbsp;&nbsp;</span>Dot-Product</a></span></li></ul></li></ul></li></ul></li><li><span><a href="#More-with-Matrices" data-toc-modified-id="More-with-Matrices-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>More with Matrices</a></span><ul class="toc-item"><li><span><a href="#Identity-Matrices" data-toc-modified-id="Identity-Matrices-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Identity Matrices</a></span><ul class="toc-item"><li><span><a href="#Identity-Matrices-in-NumPy" data-toc-modified-id="Identity-Matrices-in-NumPy-4.1.1"><span class="toc-item-num">4.1.1&nbsp;&nbsp;</span>Identity Matrices in NumPy</a></span></li></ul></li><li><span><a href="#Inverse-Matrices" data-toc-modified-id="Inverse-Matrices-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Inverse Matrices</a></span></li></ul></li><li><span><a href="#Solving-a-System-of-Linear-Equations" data-toc-modified-id="Solving-a-System-of-Linear-Equations-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Solving a System of Linear Equations</a></span><ul class="toc-item"><li><span><a href="#Representing-the-System-with-Matrices" data-toc-modified-id="Representing-the-System-with-Matrices-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Representing the System with Matrices</a></span><ul class="toc-item"><li><span><a href="#Coding-It-with-NumPy" data-toc-modified-id="Coding-It-with-NumPy-5.1.1"><span class="toc-item-num">5.1.1&nbsp;&nbsp;</span>Coding It with NumPy</a></span></li><li><span><a href="#Solve-It-Faster-with-NumPy's-linalg.solve()" data-toc-modified-id="Solve-It-Faster-with-NumPy's-linalg.solve()-5.1.2"><span class="toc-item-num">5.1.2&nbsp;&nbsp;</span>Solve It Faster with NumPy's <code>linalg.solve()</code></a></span></li></ul></li></ul></li><li><span><a href="#Solving-for-the-Line-of-Best-Fit:-Linear-Regression" data-toc-modified-id="Solving-for-the-Line-of-Best-Fit:-Linear-Regression-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Solving for the Line of Best Fit: Linear Regression</a></span><ul class="toc-item"><li><span><a href="#Linear-Algebra-Solves-the-Best-Fit-Line-Problem" data-toc-modified-id="Linear-Algebra-Solves-the-Best-Fit-Line-Problem-6.1"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>Linear Algebra Solves the Best-Fit Line Problem</a></span></li><li><span><a href="#Level-Up:-Cramer's-Rule" data-toc-modified-id="Level-Up:-Cramer's-Rule-6.2"><span class="toc-item-num">6.2&nbsp;&nbsp;</span>Level Up: Cramer's Rule</a></span></li></ul></li></ul></div>

In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

![linalg](https://online-learning.harvard.edu/sites/default/files/styles/header/public/course/3295580_orig.jpg?itok=0Rdh9m8k)

# Objectives

- Use `numpy` to construct and manipulate scalars, vectors, and matrices
- Use `numpy` to construct and manipulate identity matrices and inverse matrices
- Use `numpy` to solve systems of equations
- Describe the matrix manipulations required to solve the best-fit line problem

# What & Why of Linear Algebra

Matrices are a fundamental aspect of data science models and problems, including image processing, deep learning, NLP, and PCA. You will encounter matrices *many* times in your career as a data scientist. Matrices are a fundamental tool in **linear algebra**.

-----------

- Study of "vector spaces"; relationship of **linear** relationships
- Uses vectors, matrices, and tensors
- Mapping & dimensionality (PCA)
- Used in lots of ML applications

We'll try to put abstract ideas into the formalism of linear algebra, such as:
- data values
- images/pixels
- language (NLP)

# Scalars, Vectors, and Tensors! Oh My!

![](images/different_tensors.png)

> You can think of these values being built up to higher dimensions

## Scalars

A _scalar_ has simply a single value. Any real number can be the value of a scalar.

In [2]:
# Scalar
2


2

## Vectors

A _vector_ can be specified by with just _two_ parameters: magnitude and direction. To remind of this direction, a vector is typically denoted with an arrow above the variable representing it: $\vec{v}$ .

In a Cartesian coordinate system, a vector $\vec{v}$ will often be specified by the components defined by the coordinate system. 

In this way a vector can be embedded in a higher-dimensional space, which allows us to speak of vectors of any dimension (even though, as directed line segments, all vectors are, strictly speaking, one-dimensional).

![](https://upload.wikimedia.org/wikipedia/commons/b/ba/Vector-length.png)

> <a href="https://commons.wikimedia.org/wiki/File:Vector-length.png">Svjo</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0">CC BY-SA 4.0</a>, via Wikimedia Commons

For more on vectors, see this helpful [video](https://www.youtube.com/watch?v=fNk_zzaMoSs&list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab).

### Code for Vectors

> Note we can think of vectors as a one-dimensional object residing in multidimensional space.

In [5]:
# Vector with arange
np.arange(0,10,3)

array([0, 3, 6, 9])

In [6]:
# Vector manually
v = np.array([1, 0, 2, 1, 0, 1, 0, 1, 1])
display(v)
print('Shape:', np.shape(v))

array([1, 0, 2, 1, 0, 1, 0, 1, 1])

Shape: (9,)


In [7]:
# Other ways to define vector
x = np.linspace(-np.pi, np.pi, 10)
display(x)
print('Shape:', np.shape(x))

array([-3.14159265, -2.44346095, -1.74532925, -1.04719755, -0.34906585,
        0.34906585,  1.04719755,  1.74532925,  2.44346095,  3.14159265])

Shape: (10,)


These vectors above are usually called _row vectors_.

We can also specify _column vectors_. 

In [22]:
# Column vector from scratch
col_vector = np.array([[1], [0], [2], [1], [0], [1], [0], [1], [1]])
display(col_vector)
print('Shape:', np.shape(col_vector))

array([[1],
       [0],
       [2],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1]])

Shape: (9, 1)


In [35]:
# Reformatting or "reshaping" a row vector to a column vector
display(v)
print('Shape:', np.shape(v))


print('')
print('='*64)

col_vector = v.reshape(-1,1) # This is a common way for row -> column
display(col_vector)
print('Shape:', np.shape(col_vector))

array([1, 0, 2, 1, 0, 1, 0, 1, 1])

Shape: (9,)



array([[1],
       [0],
       [2],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1]])

Shape: (9, 1)


### Math with Vectors

#### Vector Addition

Vector addition is simple: Just add the corresponding components together:

$[8, 14] + [7, 6] = [15, 20]$

Base Python is not particularly good for non-scalar arithmetic. Make a general practice of turning to `numpy` for mathematical operations.

In [15]:
[8, 14] + [7, 6]

[8, 14, 7, 6]

In [16]:
vec_1 = np.array([8, 14])
vec_2 = np.array([7, 6])
vec_1 + vec_2

array([15, 20])

#### Vector Multiplication

In fact there are multiple ways of understanding the notion of vector multiplication. All are potentially useful, but the one that we'll likely be of most use is the *dot-product*, which is defined as follows:


$$
\begin{equation}
\begin{bmatrix}
a \\
b
\end{bmatrix}
. 
\begin{bmatrix}
c \\
d
\end{bmatrix}
=
ac + bd
\end{equation}
$$

The dot-product is the sum of the pariwise products of the vectors' entries.

In [17]:
# Let's check out the different attributes and methods available to
# a NumPy array.

# vec_1.

# There are many options. Notice that one of these options is 'dot'.
# This is our dot-product! So let's use the .dot() method to calculate
# the dot-product of our two vectors:

vec_1.dot(vec_2)

140

In [18]:
vec_1

array([ 8, 14])

In [19]:
vec_2

array([7, 6])

In [20]:
8*7 + 14*6

140

In [21]:
# We can also use '@'

vec_1 @ vec_2

140

## Matrices and Tensors

For higher dimensions we can use **matrices** to express ourselves. Suppose we had a two-variable system:

$$
\begin{align}
a_{1,1}x_1 + a_{1,2}x_2 = c_1 \\
a_{2,1}x_1 + a_{2,2}x_2 = c_2
\end{align}
$$

Using matrices, we can write this as:

$$
\begin{equation}
\begin{bmatrix}
a_{1,1} & a_{1,2} \\
a_{2,1} & a_{2,2}
\end{bmatrix}
\begin{bmatrix}
x_1 \\
x_2
\end{bmatrix} =
\begin{bmatrix}
c_1 \\
c_2
\end{bmatrix}
\end{equation}
$$

or

$A\vec{x} = \vec{c}$,

where:

- $\vec{x}$ is the _vector_ $(x_1, x_2)$;
- $\vec{c}$ is the _vector_ $(c_1, c_2)$; and
- $A$ is the _matrix_ of coefficients that describe our system:

$\begin{equation} A = 
\begin{bmatrix}
a_{1,1} & a_{1,2} \\
a_{2,1} & a_{2,2}
\end{bmatrix}
\end{equation}$

------

Technically, all of what we've talked about are **tensors**, just different ranks:

- scalar == 0th rank tensor
- vector == 1st rank tensor
    + vectors are made up from a "list" of scalars
- matrix == 2nd rank tensor
    + matrices are made up from a "list" of vectors
- 3D matrix == 3rd rank tensor
    + 3D matrices are made up from a "list" of (2D) matrices
- and so on...

> However, people are referring to the higher ranked tensors (2nd and above) when they say "tensor".

### Code for Matrices and Tensors

In [54]:
# Matrix
np.arange(2*8).reshape(2,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [55]:
# 3D Tensor
np.arange(3*4*2).reshape(3,4,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [56]:
# 4D Tensor
np.arange(2*3*4*5).reshape(2,3,4,5)

array([[[[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14],
         [ 15,  16,  17,  18,  19]],

        [[ 20,  21,  22,  23,  24],
         [ 25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34],
         [ 35,  36,  37,  38,  39]],

        [[ 40,  41,  42,  43,  44],
         [ 45,  46,  47,  48,  49],
         [ 50,  51,  52,  53,  54],
         [ 55,  56,  57,  58,  59]]],


       [[[ 60,  61,  62,  63,  64],
         [ 65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74],
         [ 75,  76,  77,  78,  79]],

        [[ 80,  81,  82,  83,  84],
         [ 85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94],
         [ 95,  96,  97,  98,  99]],

        [[100, 101, 102, 103, 104],
         [105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114],
         [115, 116, 117, 118, 119]]]])

### Math with Tensors

#### Addition

The addition of matrices is straightforward: Just add corresponding elements. In order to add two matrices $A$ and $B$, they must have the same number of rows and columns:

$\begin{bmatrix}
a_{11} & a_{12} \\
a_{21} & a_{22}
\end{bmatrix}
+
\begin{bmatrix}
b_{11} & b_{12} \\
b_{21} & b_{22}
\end{bmatrix}
=
\begin{bmatrix}
a_{11} + b_{11} & a_{12} + b_{12} \\
a_{21} + b_{21} & a_{22} + b_{22}
\end{bmatrix}
$

In [57]:
A = np.array([[1, 2], [3, 4]]) 
B = np.array([[4, 3], [2, 1]])
display(A)
display(B)

array([[1, 2],
       [3, 4]])

array([[4, 3],
       [2, 1]])

In [58]:
A + B

array([[5, 5],
       [5, 5]])

#### Dot-Product

> Just as there were different notions of "multiplication" for vectors, so too there are different notions of multiplication for matrices.

Very often when people talk about multiplying matrices they'll mean the dot-product:

$$
\begin{equation}
\begin{bmatrix}
a_{1,1} & a_{1,2} \\
a_{2,1} & a_{2,2}
\end{bmatrix}
\cdot
\begin{bmatrix}
b_{1,1} & b_{1,2} \\
b_{2,1} & b_{2,2}
\end{bmatrix}
=
\begin{bmatrix}
a_{1,1}\times b_{1,1} + a_{1,2}\times b_{2,1} & a_{1,1}\times b_{1,2} + a_{1,2}\times b_{2,2} \\
a_{2,1}\times b_{1,1} + a_{2,2}\times b_{2,1} & a_{2,1}\times b_{1,2} + a_{2,2}\times b_{2,2}
\end{bmatrix}
\end{equation}
$$

or

$$
\begin{equation}
\begin{bmatrix}
a & b \\
c & d
\end{bmatrix}
\cdot
\begin{bmatrix}
e & f \\
g & h
\end{bmatrix}
=
\begin{bmatrix}
ae + bg & af + bh \\
ce + dg & cf + dh
\end{bmatrix}
\end{equation}
$$

Take the entries in each *row* of the left matrix and multiply them, respectively, by the entries in each *column* of the right matrix, and then add them up. This is the product we calculated above with our two vectors!

We can multiply in NumPy in the same way of doing a dot product with vectors.

```python
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[11, 22], [33, 44], [55, 66]])

# Different ways to do the same dot product
AB = np.dot(A,B)
AB = A.dot(B)
AB = A @ B
```

In [88]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[11, 22], [33, 44], [55, 66]])

In [89]:
A.dot(B)

array([[242, 308],
       [539, 704]])

In [90]:
B.dot(A)

array([[ 99, 132, 165],
       [209, 286, 363],
       [319, 440, 561]])

Observe also that in order to be able to perform the dot product on two matrices A and B, **the number of columns of A must equal the number of rows of B**.

Also, **the number of rows of the product matrix will equal the number of rows of A, and the number of columns of the product matrix will equal the number of columns of B**.

> **A note about vectors and matrices**
>
> Matrix dot-multiplication is NOT commutative! In general, $AB \neq BA$.
> 
> Strictly speaking, this is true for vectors as well. Above, we multiplied the *row*-vector $(a, b)$ by the *column*-vector $(c, d)$. A row-vector is simply a matrix with only one row; a column-vector is simply a matrix with only one column. 
>
> What would be the result of multiplying the column-vector $(c, d)$ on the left by the row-vector $(a, b)$ on the right?
>
> $$\begin{equation}
    \begin{bmatrix}
        c \\
        d
    \end{bmatrix}
    \space
    \begin{bmatrix}
        a & b
    \end{bmatrix}
    =
    \begin{bmatrix}
        ca & cb \\
        da & db
    \end{bmatrix}
  \end{equation}$$

##### Exercise

Illustrate this difference between $\begin{bmatrix} a & b \end{bmatrix} \begin{bmatrix} c \\ d \end{bmatrix}$ and $\begin{bmatrix} c \\ d \end{bmatrix} \begin{bmatrix} a & b \end{bmatrix}$ in Python for $a=2, b=3, c=4$, and $d=5$.

In [91]:
# Your code here
a,b,c,d = 2,3,4,5

X = np.array([[a,b]])
# Y = np.array([c,d]).reshape(-1,1)
Y = np.array([[c,d]]).T
print(X,Y)

[[2 3]] [[4]
 [5]]


In [92]:
X.dot(Y)

array([[23]])

In [93]:
Y.dot(X)

array([[ 8, 12],
       [10, 15]])

# More with Matrices

In order to solve an equation like $A\vec{x} = \vec{c}$ for $\vec{x}$, we can't very well divide $\vec{c}$ by $A$! But there is a notion of matrix _inversion_ that is relevant here, which is analogous to multiplicative inversion. If we have an equation like $2x = 10$, we can simply multiply both sides by the multiplicative inverse of the coefficient of $x$, viz. $2^{-1}$. And here the point, of course, is that $2^{-1} \times 2 = 1$.

We'll see there is an equivalent _inverse_ for matrices. But first, we should discuss the identity matrix.

## Identity Matrices

> The **identity matrix** $I$ is the matrix containing 1's along the main diagonal (upper-left to lower-right) and 0's everywhere else:
>
> $$\begin{align}
    I_3 &= \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix} \\
    \\
    I_5 &= \begin{bmatrix} 1 & 0 & 0 & 0 & 0 & 0 \\
                           0 & 1 & 0 & 0 & 0 & 0 \\
                           0 & 0 & 1 & 0 & 0 & 0 \\
                           0 & 0 & 0 & 1 & 0 & 0 \\
                           0 & 0 & 0 & 0 & 1 & 0 \\
                           0 & 0 & 0 & 0 & 0 & 1 \\                           
            \end{bmatrix}
\end{align}$$

The identity matrix is a special matrix since any (compatible) matrix $A$ multiplied by it is the matrix itself: $AI = A$ and $IA = A$

###  Identity Matrices in NumPy

In [69]:
I5 = np.eye(5)
print(I5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [70]:
A = 42*np.ones(25).reshape(5,5)
A

array([[42., 42., 42., 42., 42.],
       [42., 42., 42., 42., 42.],
       [42., 42., 42., 42., 42.],
       [42., 42., 42., 42., 42.],
       [42., 42., 42., 42., 42.]])

In [87]:
print(I5 @ A)
print()
print(A @ I5)
print()
is_equal = (I5 @ A) == (A @ I5)
print('Both are the same:')
print(is_equal)

[[42. 42. 42. 42. 42.]
 [42. 42. 42. 42. 42.]
 [42. 42. 42. 42. 42.]
 [42. 42. 42. 42. 42.]
 [42. 42. 42. 42. 42.]]

[[42. 42. 42. 42. 42.]
 [42. 42. 42. 42. 42.]
 [42. 42. 42. 42. 42.]
 [42. 42. 42. 42. 42.]
 [42. 42. 42. 42. 42.]]

Both are the same:
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


## Inverse Matrices

In the higher-dimensional case, what we can do is to left-multiply both sides by the _inverse matrix_ of A, denoted $A^{-1}$, and here the point is that the dot-product $A^{-1}A = I$, where $I$ is the identity matrix.

Thus when we have a matrix equation $A\vec{x} = \vec{c}$, we can calculate the solution by multiplying both sides by $A^{-1}$:

$$\begin{align}
    A\vec{x}       &= \vec{c}\\
    A^{-1}A\vec{x} &= A^{-1}\vec{c}\\
    I \vec{x}      &= A^{-1}\vec{c}\\
    \vec{x}        &= A^{-1}\vec{c}\\
\end{align}$$

##### Exercise

You can produce the inverse of a matrix in `numpy` by calling `np.linalg.inv()`.

Using `numpy` arrays, find the inverse $A^{-1}$ of the matrix below:

$$A = \begin{bmatrix} 1 & -2 & 3 \\ 2 & -5 & 10 \\ 0 & 0 & 1 \end{bmatrix}$$

> Confirm this is the inverse by multiplying the matrices

In [98]:
# Your code here
A = np.array([[1,-2,3],[2,-5,10],[0,0,1]])
A

array([[ 1, -2,  3],
       [ 2, -5, 10],
       [ 0,  0,  1]])

In [99]:
np.linalg.inv(A)

array([[ 5., -2.,  5.],
       [ 2., -1.,  4.],
       [ 0.,  0.,  1.]])

In [102]:
A.dot(np.linalg.inv(A))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [103]:
np.linalg.inv(A).dot(A)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Solving a System of Linear Equations

Solving a system of equations can take a lot of work

$$ \begin{align}
 x - 2y + 3z &= 9 \\
 2x - 5y + 10z &= 4 \\
  6z &= 0 
\end{align}$$

## Representing the System with Matrices

But we can make it easier by writing it in matrix form

$$ 
\begin{pmatrix} 
    1 & -2 & 3 \\
    2 & -5 & 10 \\
    0 & 0 & 6
\end{pmatrix}
\cdot
\begin{pmatrix} 
    x \\
    y \\
    z
\end{pmatrix}
=
\begin{pmatrix} 
    9 \\
    4 \\
    0
\end{pmatrix}
$$

We can think of this in the abstract:
$$ A \cdot \vec{x} = \vec{b} $$
$$ A^{-1} \cdot A \cdot \vec{x} = A^{-1} \cdot \vec{b} $$
$$ I \cdot \vec{x} = A^{-1} \cdot \vec{b} $$
$$ \vec{x} = A^{-1} \cdot \vec{b} $$

### Coding It with NumPy

Let's try solving the system with matrices:

$$ \begin{align}
 1 - 2y + 3z &= 9 \\
 2x - 5y + 10z &= 4 \\
  6z &= 0 
\end{align}$$

First define the system's matrices:

$$ 
\begin{pmatrix} 
    1 & -2 & 3 \\
    2 & -5 & 10 \\
    0 & 0 & 6
\end{pmatrix}
\cdot
\begin{pmatrix} 
    x \\
    y \\
    z
\end{pmatrix}
=
\begin{pmatrix} 
    9 \\
    4 \\
    0
\end{pmatrix}
$$

to 

$$ A \cdot \vec{x} = \vec{b} $$

In [104]:
# Create A
A = np.array([[1, -2, 3],
              [2, -5, 10],
              [0, 0, 6]])

In [105]:
# Create b
b = np.array([[9,4,0]]).T

In [106]:
print('A:')
print(A)
print()
print('b:')
print(b)

A:
[[ 1 -2  3]
 [ 2 -5 10]
 [ 0  0  6]]

b:
[[9]
 [4]
 [0]]


Find the inverse

In [107]:
A_inverse = np.linalg.inv(A)

Getting the solution

In [108]:
A_inverse.dot(b)

array([[37.],
       [14.],
       [ 0.]])

### Solve It Faster with NumPy's `linalg.solve()`

NumPy's ```linalg``` module has a ```.solve()``` method that you can use to solve a system of linear equations!

In particular, it will solve for the vector $\vec{x}$ in the equation $A\vec{x} = b$. You should know that, "under the hood", the ```.solve()``` method does NOT compute the inverse matrix $A^{-1}$. This is largely because of the enormous expense of directly computing a matrix inverse, which takes $\mathcal{O}(n^3)$ time.

Check out [this discussion](https://stackoverflow.com/questions/31256252/why-does-numpy-linalg-solve-offer-more-precise-matrix-inversions-than-numpy-li) on stackoverflow for more on the differences between using `.solve()` and `.inv()`.

And check out the documentation for ```.solve()``` [here](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.solve.html).

In [110]:
# Let's use the .solve() method to solve this system of equations

A = np.array([
    [1, -2,  3],
    [2, -5, 10],
    [0,  0,  6]
])

b = np.array([9, 4, 0]).reshape(3, 1)

In [111]:
np.linalg.solve(A, b)

array([[37.],
       [14.],
       [ 0.]])

Again, we could just solve our matrix equation by calculating the inverse of our matrix $X$ and then multiplying by $y$:

In [112]:
np.linalg.inv(A).dot(b)

array([[37.],
       [14.],
       [ 0.]])

But the time difference is striking:

In [115]:
%timeit np.linalg.inv(A).dot(b)

25.2 µs ± 1.38 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [116]:
%timeit np.linalg.solve(A, b)

6.72 µs ± 138 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Even for a (tiny!) 3x3 matrix, the cost of computing the inverse directly is evident.

# Solving for the Line of Best Fit: Linear Regression

Consider a typical dataset and the associated multiple linear regression problem. We have many observations (rows), each of which consists of a set of values both for the predictors (columns, i.e. the independent variables) and for the target (the dependent variable).

We can think of the values of the independent variables as our matrix $A$ of coefficients and of the values of the dependent variable as our output vector $\vec{c}$.

The task here is, in effect, to solve for $\vec{\beta}$, where we have that $A\vec{\beta} = \vec{c}$, except in general we'll have more rows than columns. This is why we won't in general be computing matrix inverses. (They're computationally expensive, anyway.) This is also why we have a problem requiring not a direct solution but rather an optimization--in our case, a best-fit line.

Using $z$ for our independent variables and $y$ for our dependent variable, we have:


\begin{equation}
\beta_1\begin{bmatrix}
z_{1,1} \\
. \\
. \\
. \\
z_{m,1}
\end{bmatrix} +
... + \beta_n\begin{bmatrix}
z_{1,n} \\
. \\
. \\
. \\
z_{m,n}
\end{bmatrix} \approx \begin{bmatrix}
y_1 \\
.  \\
.  \\
.  \\
y_m
\end{bmatrix}
\end{equation}

## Linear Algebra Solves the Best-Fit Line Problem

If we have a matrix of predictors $X$ and a target column $y$, we can express $\vec{\beta}$, the vectorized parameters of the best-fit line, as  follows:

$\large\vec{\beta} = (X^TX)^{-1}X^Ty$.

$(X^TX)^{-1}X^T$ is sometimes called the *pseudo-inverse* of $X$. We'll have more to say about this in a future lesson when we talk about the singular value decomposition.

Let's see this in action:

In [118]:
preds = np.array(list(zip(np.random.normal(size=10),
                          np.array(np.random.normal(size=10, loc=2)))))
target = np.array(np.random.exponential(size=10))

In [119]:
preds

array([[-0.07335735,  4.04107672],
       [-1.33680924,  2.75124888],
       [-0.02918132,  1.31868096],
       [-0.55207427,  1.27972014],
       [ 0.31291837,  3.22990727],
       [ 0.10335366,  2.47275814],
       [ 0.03938958,  1.86181167],
       [ 0.76098772,  1.46874543],
       [ 0.39908729,  2.67139956],
       [-0.27057822,  0.21719174]])

In [120]:
np.linalg.inv(preds.T.dot(preds)).dot(preds.T).dot(target)

array([0.43428489, 0.39431031])

In [121]:
LinearRegression(fit_intercept=False).fit(preds, target).coef_

array([0.43428489, 0.39431031])

In [122]:
%timeit np.linalg.inv(preds.T.dot(preds)).dot(preds.T).dot(target)

24.3 µs ± 3.2 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [123]:
%timeit LinearRegression(fit_intercept=False).fit(preds, target).coef_

174 µs ± 10.9 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


## Level Up: Cramer's Rule

Cramer's Rule tells us how to solve a system of linear equations in terms of the [determinant](https://en.wikipedia.org/wiki/Determinant) of the data matrix:

If we have $A\vec{x} = \vec{b}$, where $\vec{x} = \begin{bmatrix}x_1 \\ . \\ . \\ . \\ x_n \end{bmatrix}$, then $x_i = \frac{|A_i|}{|A|}$,

where $A_i$ is the matrix formed by replacing the $i$'th column of $A$ with $\vec{b}$.

In [124]:
# Using the A and B from above.

A = np.array([
    [1, -2,  3],
    [2, -5, 10],
    [0,  0,  6]
])

b = np.array([9, 4, 0]).reshape(3, 1)

display(A)
display(b)

array([[ 1, -2,  3],
       [ 2, -5, 10],
       [ 0,  0,  6]])

array([[9],
       [4],
       [0]])

In [125]:
# Cramer's Rule.

det_A = np.linalg.det(A)
det_A

-6.0

In [126]:
x1_num = np.hstack((b, A[:, 1:]))
x1_num

array([[ 9, -2,  3],
       [ 4, -5, 10],
       [ 0,  0,  6]])

In [127]:
x2_num = np.hstack((A[:, :1], b, A[:, -1:]))
x2_num

array([[ 1,  9,  3],
       [ 2,  4, 10],
       [ 0,  0,  6]])

In [128]:
x3_num = np.hstack((A[:, :2], b))
x3_num

array([[ 1, -2,  9],
       [ 2, -5,  4],
       [ 0,  0,  0]])

In [129]:
print(np.linalg.det(x1_num) / det_A)
print(np.linalg.det(x2_num) / det_A)
print(np.linalg.det(x3_num) / det_A)

37.00000000000003
13.999999999999998
-0.0
